name: 🚀 Java CI with Maven - Build, Test & Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: 🧪 Compile, Test and Measure Coverage
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 💾 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 🔨 Build, test and generate JaCoCo coverage report
        run: mvn clean verify

      - name: 📊 Upload JaCoCo coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage
          path: target/site/jacoco

      - name: ✅ Confirm test success
        run: echo "✅ All tests passed successfully"
